-- MySQL Script generated by MySQL Workbench
-- Wed May 29 15:37:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema conversationdiscovery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conversationdiscovery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conversationdiscovery` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `conversationdiscovery` ;

-- -----------------------------------------------------
-- Table `conversationdiscovery`.`CAA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversationdiscovery`.`CAA` (
  `caaId` VARCHAR(150),
  `client` VARCHAR(50) NULL,
  `app` VARCHAR(50) NULL,
  `account` VARCHAR(50) NULL,
  PRIMARY KEY (`caaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversationdiscovery`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversationdiscovery`.`project` (
  `projectId` VARCHAR(50) NOT NULL,
  `caaId` VARCHAR(150),
  `projectName` VARCHAR(50) NOT NULL,
  `datasetName` VARCHAR(50) NOT NULL,
  `modified` BIGINT DEFAULT NULL,
  `modifiedBy` VARCHAR(50) DEFAULT NULL,
  `created` BIGINT NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  `projectDescription` VARCHAR(150) DEFAULT NULL,
  `datasetURL` VARCHAR(250) DEFAULT NULL,
  `projectStatus` VARCHAR(50) NOT NULL,
  `projectStatusDescription` VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (`projectId`),
  INDEX `fk_PROJECT_CAA_idx` (`caaId` ASC),
  CONSTRAINT `fk_PROJECT_CAA`
    FOREIGN KEY (`caaId`)
    REFERENCES `conversationdiscovery`.`CAA` (`caaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `projectName_CAA`
    UNIQUE(`caaId`, `projectName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversationdiscovery`.`Run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversationdiscovery`.`run` (
  `runID` VARCHAR(50) NOT NULL,
  `projectID` VARCHAR(50) NOT NULL,
  `runName` VARCHAR(50) NOT NULL,
  `runDescription` VARCHAR(250) NULL,
  `numOfTurns` INT NOT NULL,
  `numOfClusters` INT NOT NULL,
  `stopWords` TEXT DEFAULT NULL,
  `modified` BIGINT DEFAULT NULL,
  `modifiedBy` VARCHAR(50) DEFAULT NULL,
  `created` BIGINT NOT NULL,
  `createdBy` VARCHAR(50) NOT NULL,
  `runStatus` VARCHAR(50) NOT NULL,
  `runStatusDescription` VARCHAR(250) DEFAULT NULL,
  `starred` INT NOT NULL,
  `resultURL` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`runID`),
  INDEX `fk_Run_Project1_idx` (`projectID` ASC),
  CONSTRAINT `fk_Run_Project1`
    FOREIGN KEY (`projectID`)
    REFERENCES `conversationdiscovery`.`project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 CONSTRAINT `projectID_runName`
    UNIQUE(`projectID`, `runName`))

ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
